service: calculadora-serverless

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1

functions:
  operaciones:
    handler: handler.operaciones
    events:
      - http:
          path: calcular
          method: post
          cors: true

plugins:
  - serverless-offline
